### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by willettk**
Shorten the URLs for GZ2.

### CODE REVIEW

**Comment by astopy** [comment]
This and #31 should be deployed now.

**Comment by willettk** [comment]
Thanks, @astopy!

**Comment by willettk** [comment]
Actually, pause - the GZH structure is there, but the links to the actual
data give a 404. Eg,
http://zooniverse-data.s3.amazonaws.com/galaxy-zoo-hubble/gz_hubble_faded.vot.gz

Are the files not yet in that directory, or is there an issue with global
permissions?

**Comment by astopy** [comment]
Looks like the files aren't on there... are they already up somewhere that I can grab them from? I'll upload them if so.

**Comment by willettk** [comment]
I asked @vrooje if she could do it, but she's been really busy with
observing this week. If you have a moment to take care of it, that'd be
great. Files are all on this Dropbox folder.

https://www.dropbox.com/sh/l0llf1m8y654wey/AAAWpBMfg6u7msnFRsiu3MQua?dl=0


On Mon, Oct 10, 2016 at 11:22 AM Adam McMaster <notifications@github.com>
wrote:

Looks like the files aren't on there... are they already up somewhere that
I can grab them from? I'll upload them if so.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zooniverse/data.galaxyzoo.org/pull/32#issuecomment-252655006>,
or mute the thread

**Comment by astopy** [comment]
Cool, they should all be up now.

**Pull request merged**
